package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Allowance generated by hbm2java
 */
public class Allowance  implements java.io.Serializable {


     private Integer idAllowance;
     private String allowancName;
     private String isdelete;
     private String createdBy;
     private String isAprove;
     private Set staffHasAllowances = new HashSet(0);

    public Allowance() {
    }

    public Allowance(String allowancName, String isdelete, String createdBy, String isAprove, Set staffHasAllowances) {
       this.allowancName = allowancName;
       this.isdelete = isdelete;
       this.createdBy = createdBy;
       this.isAprove = isAprove;
       this.staffHasAllowances = staffHasAllowances;
    }
   
    public Integer getIdAllowance() {
        return this.idAllowance;
    }
    
    public void setIdAllowance(Integer idAllowance) {
        this.idAllowance = idAllowance;
    }
    public String getAllowancName() {
        return this.allowancName;
    }
    
    public void setAllowancName(String allowancName) {
        this.allowancName = allowancName;
    }
    public String getIsdelete() {
        return this.isdelete;
    }
    
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getIsAprove() {
        return this.isAprove;
    }
    
    public void setIsAprove(String isAprove) {
        this.isAprove = isAprove;
    }
    public Set getStaffHasAllowances() {
        return this.staffHasAllowances;
    }
    
    public void setStaffHasAllowances(Set staffHasAllowances) {
        this.staffHasAllowances = staffHasAllowances;
    }




}


