package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer idBranch;
     private String branchNo;
     private String branchName;
     private String address1;
     private String address2;
     private String city;
     private String contact1;
     private String contact2;
     private String isActive;
     private Set centers = new HashSet(0);

    public Branch() {
    }

    public Branch(String branchNo, String branchName, String address1, String address2, String city, String contact1, String contact2, String isActive, Set centers) {
       this.branchNo = branchNo;
       this.branchName = branchName;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.contact1 = contact1;
       this.contact2 = contact2;
       this.isActive = isActive;
       this.centers = centers;
    }
   
    public Integer getIdBranch() {
        return this.idBranch;
    }
    
    public void setIdBranch(Integer idBranch) {
        this.idBranch = idBranch;
    }
    public String getBranchNo() {
        return this.branchNo;
    }
    
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getContact1() {
        return this.contact1;
    }
    
    public void setContact1(String contact1) {
        this.contact1 = contact1;
    }
    public String getContact2() {
        return this.contact2;
    }
    
    public void setContact2(String contact2) {
        this.contact2 = contact2;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Set getCenters() {
        return this.centers;
    }
    
    public void setCenters(Set centers) {
        this.centers = centers;
    }




}


