package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Center generated by hbm2java
 */
public class Center  implements java.io.Serializable {


     private Integer idCenter;
     private Branch branch;
     private String centerName;
     private String centerDay;
     private String centertime;
     private String isApprove;
     private String isActive;
     private String createdBy;
     private String centerNo;
     private Set centerHasStaffs = new HashSet(0);
     private Set memberses = new HashSet(0);

    public Center() {
    }

	
    public Center(Branch branch) {
        this.branch = branch;
    }
    public Center(Branch branch, String centerName, String centerDay, String centertime, String isApprove, String isActive, String createdBy, String centerNo, Set centerHasStaffs, Set memberses) {
       this.branch = branch;
       this.centerName = centerName;
       this.centerDay = centerDay;
       this.centertime = centertime;
       this.isApprove = isApprove;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.centerNo = centerNo;
       this.centerHasStaffs = centerHasStaffs;
       this.memberses = memberses;
    }
   
    public Integer getIdCenter() {
        return this.idCenter;
    }
    
    public void setIdCenter(Integer idCenter) {
        this.idCenter = idCenter;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public String getCenterName() {
        return this.centerName;
    }
    
    public void setCenterName(String centerName) {
        this.centerName = centerName;
    }
    public String getCenterDay() {
        return this.centerDay;
    }
    
    public void setCenterDay(String centerDay) {
        this.centerDay = centerDay;
    }
    public String getCentertime() {
        return this.centertime;
    }
    
    public void setCentertime(String centertime) {
        this.centertime = centertime;
    }
    public String getIsApprove() {
        return this.isApprove;
    }
    
    public void setIsApprove(String isApprove) {
        this.isApprove = isApprove;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCenterNo() {
        return this.centerNo;
    }
    
    public void setCenterNo(String centerNo) {
        this.centerNo = centerNo;
    }
    public Set getCenterHasStaffs() {
        return this.centerHasStaffs;
    }
    
    public void setCenterHasStaffs(Set centerHasStaffs) {
        this.centerHasStaffs = centerHasStaffs;
    }
    public Set getMemberses() {
        return this.memberses;
    }
    
    public void setMemberses(Set memberses) {
        this.memberses = memberses;
    }




}


