package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * DayEnd generated by hbm2java
 */
public class DayEnd  implements java.io.Serializable {


     private Integer idDayEnd;
     private String dayEndDate;
     private String dayEndTime;

    public DayEnd() {
    }

    public DayEnd(String dayEndDate, String dayEndTime) {
       this.dayEndDate = dayEndDate;
       this.dayEndTime = dayEndTime;
    }
   
    public Integer getIdDayEnd() {
        return this.idDayEnd;
    }
    
    public void setIdDayEnd(Integer idDayEnd) {
        this.idDayEnd = idDayEnd;
    }
    public String getDayEndDate() {
        return this.dayEndDate;
    }
    
    public void setDayEndDate(String dayEndDate) {
        this.dayEndDate = dayEndDate;
    }
    public String getDayEndTime() {
        return this.dayEndTime;
    }
    
    public void setDayEndTime(String dayEndTime) {
        this.dayEndTime = dayEndTime;
    }




}


