package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Deductions generated by hbm2java
 */
public class Deductions  implements java.io.Serializable {


     private Integer idDeductions;
     private String deductionType;
     private String isDelete;
     private String createdBy;
     private Set staffHasDeductionses = new HashSet(0);

    public Deductions() {
    }

    public Deductions(String deductionType, String isDelete, String createdBy, Set staffHasDeductionses) {
       this.deductionType = deductionType;
       this.isDelete = isDelete;
       this.createdBy = createdBy;
       this.staffHasDeductionses = staffHasDeductionses;
    }
   
    public Integer getIdDeductions() {
        return this.idDeductions;
    }
    
    public void setIdDeductions(Integer idDeductions) {
        this.idDeductions = idDeductions;
    }
    public String getDeductionType() {
        return this.deductionType;
    }
    
    public void setDeductionType(String deductionType) {
        this.deductionType = deductionType;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Set getStaffHasDeductionses() {
        return this.staffHasDeductionses;
    }
    
    public void setStaffHasDeductionses(Set staffHasDeductionses) {
        this.staffHasDeductionses = staffHasDeductionses;
    }




}


