package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Denimationcah generated by hbm2java
 */
public class Denimationcah  implements java.io.Serializable {


     private Integer idDenimationCah;
     private Denimation denimation;
     private Integer n5000;
     private Integer n2000;
     private Integer n1000;
     private Integer n500;
     private Integer n100;
     private Integer n50;
     private Integer n20;
     private Integer n10;
     private Double coins;
     private Double total;
     private String slipNo;

    public Denimationcah() {
    }

	
    public Denimationcah(Denimation denimation) {
        this.denimation = denimation;
    }
    public Denimationcah(Denimation denimation, Integer n5000, Integer n2000, Integer n1000, Integer n500, Integer n100, Integer n50, Integer n20, Integer n10, Double coins, Double total, String slipNo) {
       this.denimation = denimation;
       this.n5000 = n5000;
       this.n2000 = n2000;
       this.n1000 = n1000;
       this.n500 = n500;
       this.n100 = n100;
       this.n50 = n50;
       this.n20 = n20;
       this.n10 = n10;
       this.coins = coins;
       this.total = total;
       this.slipNo = slipNo;
    }
   
    public Integer getIdDenimationCah() {
        return this.idDenimationCah;
    }
    
    public void setIdDenimationCah(Integer idDenimationCah) {
        this.idDenimationCah = idDenimationCah;
    }
    public Denimation getDenimation() {
        return this.denimation;
    }
    
    public void setDenimation(Denimation denimation) {
        this.denimation = denimation;
    }
    public Integer getN5000() {
        return this.n5000;
    }
    
    public void setN5000(Integer n5000) {
        this.n5000 = n5000;
    }
    public Integer getN2000() {
        return this.n2000;
    }
    
    public void setN2000(Integer n2000) {
        this.n2000 = n2000;
    }
    public Integer getN1000() {
        return this.n1000;
    }
    
    public void setN1000(Integer n1000) {
        this.n1000 = n1000;
    }
    public Integer getN500() {
        return this.n500;
    }
    
    public void setN500(Integer n500) {
        this.n500 = n500;
    }
    public Integer getN100() {
        return this.n100;
    }
    
    public void setN100(Integer n100) {
        this.n100 = n100;
    }
    public Integer getN50() {
        return this.n50;
    }
    
    public void setN50(Integer n50) {
        this.n50 = n50;
    }
    public Integer getN20() {
        return this.n20;
    }
    
    public void setN20(Integer n20) {
        this.n20 = n20;
    }
    public Integer getN10() {
        return this.n10;
    }
    
    public void setN10(Integer n10) {
        this.n10 = n10;
    }
    public Double getCoins() {
        return this.coins;
    }
    
    public void setCoins(Double coins) {
        this.coins = coins;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getSlipNo() {
        return this.slipNo;
    }
    
    public void setSlipNo(String slipNo) {
        this.slipNo = slipNo;
    }




}


