package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Denimation generated by hbm2java
 */
public class Denimation  implements java.io.Serializable {


     private Integer idDenimation;
     private Staff staff;
     private String date;
     private Double exchangeCash;
     private Double centerCollection;
     private Double npcollection;
     private Double memberFee;
     private Double incomeAmount;
     private Double totalLoanAmount;
     private Double expences;
     private Double totalBalance;
     private Double short_;
     private Double extras;
     private Double shortAndExtraBalance;
     private Set denimationcahs = new HashSet(0);

    public Denimation() {
    }

    public Denimation(Staff staff, String date, Double exchangeCash, Double centerCollection, Double npcollection, Double memberFee, Double incomeAmount, Double totalLoanAmount, Double expences, Double totalBalance, Double short_, Double extras, Double shortAndExtraBalance, Set denimationcahs) {
       this.staff = staff;
       this.date = date;
       this.exchangeCash = exchangeCash;
       this.centerCollection = centerCollection;
       this.npcollection = npcollection;
       this.memberFee = memberFee;
       this.incomeAmount = incomeAmount;
       this.totalLoanAmount = totalLoanAmount;
       this.expences = expences;
       this.totalBalance = totalBalance;
       this.short_ = short_;
       this.extras = extras;
       this.shortAndExtraBalance = shortAndExtraBalance;
       this.denimationcahs = denimationcahs;
    }
   
    public Integer getIdDenimation() {
        return this.idDenimation;
    }
    
    public void setIdDenimation(Integer idDenimation) {
        this.idDenimation = idDenimation;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Double getExchangeCash() {
        return this.exchangeCash;
    }
    
    public void setExchangeCash(Double exchangeCash) {
        this.exchangeCash = exchangeCash;
    }
    public Double getCenterCollection() {
        return this.centerCollection;
    }
    
    public void setCenterCollection(Double centerCollection) {
        this.centerCollection = centerCollection;
    }
    public Double getNpcollection() {
        return this.npcollection;
    }
    
    public void setNpcollection(Double npcollection) {
        this.npcollection = npcollection;
    }
    public Double getMemberFee() {
        return this.memberFee;
    }
    
    public void setMemberFee(Double memberFee) {
        this.memberFee = memberFee;
    }
    public Double getIncomeAmount() {
        return this.incomeAmount;
    }
    
    public void setIncomeAmount(Double incomeAmount) {
        this.incomeAmount = incomeAmount;
    }
    public Double getTotalLoanAmount() {
        return this.totalLoanAmount;
    }
    
    public void setTotalLoanAmount(Double totalLoanAmount) {
        this.totalLoanAmount = totalLoanAmount;
    }
    public Double getExpences() {
        return this.expences;
    }
    
    public void setExpences(Double expences) {
        this.expences = expences;
    }
    public Double getTotalBalance() {
        return this.totalBalance;
    }
    
    public void setTotalBalance(Double totalBalance) {
        this.totalBalance = totalBalance;
    }
    public Double getShort_() {
        return this.short_;
    }
    
    public void setShort_(Double short_) {
        this.short_ = short_;
    }
    public Double getExtras() {
        return this.extras;
    }
    
    public void setExtras(Double extras) {
        this.extras = extras;
    }
    public Double getShortAndExtraBalance() {
        return this.shortAndExtraBalance;
    }
    
    public void setShortAndExtraBalance(Double shortAndExtraBalance) {
        this.shortAndExtraBalance = shortAndExtraBalance;
    }
    public Set getDenimationcahs() {
        return this.denimationcahs;
    }
    
    public void setDenimationcahs(Set denimationcahs) {
        this.denimationcahs = denimationcahs;
    }




}


