package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Legalaction generated by hbm2java
 */
public class Legalaction  implements java.io.Serializable {


     private Integer idLegalAction;
     private Loan loan;
     private Members members;
     private String date;
     private String reason;
     private String description;
     private String isActive;
     private String isAproved;
     private String createdBy;

    public Legalaction() {
    }

	
    public Legalaction(Loan loan, Members members) {
        this.loan = loan;
        this.members = members;
    }
    public Legalaction(Loan loan, Members members, String date, String reason, String description, String isActive, String isAproved, String createdBy) {
       this.loan = loan;
       this.members = members;
       this.date = date;
       this.reason = reason;
       this.description = description;
       this.isActive = isActive;
       this.isAproved = isAproved;
       this.createdBy = createdBy;
    }
   
    public Integer getIdLegalAction() {
        return this.idLegalAction;
    }
    
    public void setIdLegalAction(Integer idLegalAction) {
        this.idLegalAction = idLegalAction;
    }
    public Loan getLoan() {
        return this.loan;
    }
    
    public void setLoan(Loan loan) {
        this.loan = loan;
    }
    public Members getMembers() {
        return this.members;
    }
    
    public void setMembers(Members members) {
        this.members = members;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getIsAproved() {
        return this.isAproved;
    }
    
    public void setIsAproved(String isAproved) {
        this.isAproved = isAproved;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


