package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loan generated by hbm2java
 */
public class Loan  implements java.io.Serializable {


     private Integer idLoan;
     private Members members;
     private String contractNo;
     private Double loanAmount;
     private Double loanInterest;
     private Integer loanPeriod;
     private Double loanInstallment;
     private String memberfee;
     private String loanIndex;
     private String repaymentDay;
     private String loanDate;
     private String status;
     private String garanter1;
     private String garanter2;
     private String isAprove;
     private String isActive;
     private String createBy;
     private Double renewAmount;
     private String issueDate;
     private Set repayments = new HashSet(0);
     private Set loancancellations = new HashSet(0);
     private Set legalactions = new HashSet(0);

    public Loan() {
    }

	
    public Loan(Members members) {
        this.members = members;
    }
    public Loan(Members members, String contractNo, Double loanAmount, Double loanInterest, Integer loanPeriod, Double loanInstallment, String memberfee, String loanIndex, String repaymentDay, String loanDate, String status, String garanter1, String garanter2, String isAprove, String isActive, String createBy, Double renewAmount, String issueDate, Set repayments, Set loancancellations, Set legalactions) {
       this.members = members;
       this.contractNo = contractNo;
       this.loanAmount = loanAmount;
       this.loanInterest = loanInterest;
       this.loanPeriod = loanPeriod;
       this.loanInstallment = loanInstallment;
       this.memberfee = memberfee;
       this.loanIndex = loanIndex;
       this.repaymentDay = repaymentDay;
       this.loanDate = loanDate;
       this.status = status;
       this.garanter1 = garanter1;
       this.garanter2 = garanter2;
       this.isAprove = isAprove;
       this.isActive = isActive;
       this.createBy = createBy;
       this.renewAmount = renewAmount;
       this.issueDate = issueDate;
       this.repayments = repayments;
       this.loancancellations = loancancellations;
       this.legalactions = legalactions;
    }
   
    public Integer getIdLoan() {
        return this.idLoan;
    }
    
    public void setIdLoan(Integer idLoan) {
        this.idLoan = idLoan;
    }
    public Members getMembers() {
        return this.members;
    }
    
    public void setMembers(Members members) {
        this.members = members;
    }
    public String getContractNo() {
        return this.contractNo;
    }
    
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }
    public Double getLoanAmount() {
        return this.loanAmount;
    }
    
    public void setLoanAmount(Double loanAmount) {
        this.loanAmount = loanAmount;
    }
    public Double getLoanInterest() {
        return this.loanInterest;
    }
    
    public void setLoanInterest(Double loanInterest) {
        this.loanInterest = loanInterest;
    }
    public Integer getLoanPeriod() {
        return this.loanPeriod;
    }
    
    public void setLoanPeriod(Integer loanPeriod) {
        this.loanPeriod = loanPeriod;
    }
    public Double getLoanInstallment() {
        return this.loanInstallment;
    }
    
    public void setLoanInstallment(Double loanInstallment) {
        this.loanInstallment = loanInstallment;
    }
    public String getMemberfee() {
        return this.memberfee;
    }
    
    public void setMemberfee(String memberfee) {
        this.memberfee = memberfee;
    }
    public String getLoanIndex() {
        return this.loanIndex;
    }
    
    public void setLoanIndex(String loanIndex) {
        this.loanIndex = loanIndex;
    }
    public String getRepaymentDay() {
        return this.repaymentDay;
    }
    
    public void setRepaymentDay(String repaymentDay) {
        this.repaymentDay = repaymentDay;
    }
    public String getLoanDate() {
        return this.loanDate;
    }
    
    public void setLoanDate(String loanDate) {
        this.loanDate = loanDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getGaranter1() {
        return this.garanter1;
    }
    
    public void setGaranter1(String garanter1) {
        this.garanter1 = garanter1;
    }
    public String getGaranter2() {
        return this.garanter2;
    }
    
    public void setGaranter2(String garanter2) {
        this.garanter2 = garanter2;
    }
    public String getIsAprove() {
        return this.isAprove;
    }
    
    public void setIsAprove(String isAprove) {
        this.isAprove = isAprove;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
    public Double getRenewAmount() {
        return this.renewAmount;
    }
    
    public void setRenewAmount(Double renewAmount) {
        this.renewAmount = renewAmount;
    }
    public String getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }
    public Set getRepayments() {
        return this.repayments;
    }
    
    public void setRepayments(Set repayments) {
        this.repayments = repayments;
    }
    public Set getLoancancellations() {
        return this.loancancellations;
    }
    
    public void setLoancancellations(Set loancancellations) {
        this.loancancellations = loancancellations;
    }
    public Set getLegalactions() {
        return this.legalactions;
    }
    
    public void setLegalactions(Set legalactions) {
        this.legalactions = legalactions;
    }




}


