package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * LoanAccount generated by hbm2java
 */
public class LoanAccount  implements java.io.Serializable {


     private Integer idLoanAcc;
     private String accDate;
     private String description;
     private Double credit;
     private Double debit;
     private String isActive;
     private String createBy;

    public LoanAccount() {
    }

    public LoanAccount(String accDate, String description, Double credit, Double debit, String isActive, String createBy) {
       this.accDate = accDate;
       this.description = description;
       this.credit = credit;
       this.debit = debit;
       this.isActive = isActive;
       this.createBy = createBy;
    }
   
    public Integer getIdLoanAcc() {
        return this.idLoanAcc;
    }
    
    public void setIdLoanAcc(Integer idLoanAcc) {
        this.idLoanAcc = idLoanAcc;
    }
    public String getAccDate() {
        return this.accDate;
    }
    
    public void setAccDate(String accDate) {
        this.accDate = accDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getCredit() {
        return this.credit;
    }
    
    public void setCredit(Double credit) {
        this.credit = credit;
    }
    public Double getDebit() {
        return this.debit;
    }
    
    public void setDebit(Double debit) {
        this.debit = debit;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }




}


