package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Loancancellation generated by hbm2java
 */
public class Loancancellation  implements java.io.Serializable {


     private Integer idLoanCancellation;
     private Loan loan;
     private String date;
     private String reason;
     private String isAproved;
     private String isActive;
     private String creaedBy;

    public Loancancellation() {
    }

	
    public Loancancellation(Loan loan) {
        this.loan = loan;
    }
    public Loancancellation(Loan loan, String date, String reason, String isAproved, String isActive, String creaedBy) {
       this.loan = loan;
       this.date = date;
       this.reason = reason;
       this.isAproved = isAproved;
       this.isActive = isActive;
       this.creaedBy = creaedBy;
    }
   
    public Integer getIdLoanCancellation() {
        return this.idLoanCancellation;
    }
    
    public void setIdLoanCancellation(Integer idLoanCancellation) {
        this.idLoanCancellation = idLoanCancellation;
    }
    public Loan getLoan() {
        return this.loan;
    }
    
    public void setLoan(Loan loan) {
        this.loan = loan;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getIsAproved() {
        return this.isAproved;
    }
    
    public void setIsAproved(String isAproved) {
        this.isAproved = isAproved;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreaedBy() {
        return this.creaedBy;
    }
    
    public void setCreaedBy(String creaedBy) {
        this.creaedBy = creaedBy;
    }




}


