package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idLogin;
     private Staff staff;
     private String userName;
     private String password;
     private String type;
     private String setDate;
     private String loginBlock;
     private String isActive;
     private String isAprove;
     private String createdBy;

    public Login() {
    }

	
    public Login(Staff staff) {
        this.staff = staff;
    }
    public Login(Staff staff, String userName, String password, String type, String setDate, String loginBlock, String isActive, String isAprove, String createdBy) {
       this.staff = staff;
       this.userName = userName;
       this.password = password;
       this.type = type;
       this.setDate = setDate;
       this.loginBlock = loginBlock;
       this.isActive = isActive;
       this.isAprove = isAprove;
       this.createdBy = createdBy;
    }
   
    public Integer getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getSetDate() {
        return this.setDate;
    }
    
    public void setSetDate(String setDate) {
        this.setDate = setDate;
    }
    public String getLoginBlock() {
        return this.loginBlock;
    }
    
    public void setLoginBlock(String loginBlock) {
        this.loginBlock = loginBlock;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getIsAprove() {
        return this.isAprove;
    }
    
    public void setIsAprove(String isAprove) {
        this.isAprove = isAprove;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


