package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Printvoucher generated by hbm2java
 */
public class Printvoucher  implements java.io.Serializable {


     private int idPrintVoucher;
     private String date;
     private String amount;
     private String isactive;
     private String isAprove;
     private String createdBy;

    public Printvoucher() {
    }

	
    public Printvoucher(int idPrintVoucher) {
        this.idPrintVoucher = idPrintVoucher;
    }
    public Printvoucher(int idPrintVoucher, String date, String amount, String isactive, String isAprove, String createdBy) {
       this.idPrintVoucher = idPrintVoucher;
       this.date = date;
       this.amount = amount;
       this.isactive = isactive;
       this.isAprove = isAprove;
       this.createdBy = createdBy;
    }
   
    public int getIdPrintVoucher() {
        return this.idPrintVoucher;
    }
    
    public void setIdPrintVoucher(int idPrintVoucher) {
        this.idPrintVoucher = idPrintVoucher;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getIsactive() {
        return this.isactive;
    }
    
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }
    public String getIsAprove() {
        return this.isAprove;
    }
    
    public void setIsAprove(String isAprove) {
        this.isAprove = isAprove;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


