package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Repaymentcancellation generated by hbm2java
 */
public class Repaymentcancellation  implements java.io.Serializable {


     private Integer idRepaymentCancellation;
     private Repayment repayment;
     private String date;
     private String reason;
     private String isAproved;
     private String isActive;
     private String createdBy;

    public Repaymentcancellation() {
    }

	
    public Repaymentcancellation(Repayment repayment) {
        this.repayment = repayment;
    }
    public Repaymentcancellation(Repayment repayment, String date, String reason, String isAproved, String isActive, String createdBy) {
       this.repayment = repayment;
       this.date = date;
       this.reason = reason;
       this.isAproved = isAproved;
       this.isActive = isActive;
       this.createdBy = createdBy;
    }
   
    public Integer getIdRepaymentCancellation() {
        return this.idRepaymentCancellation;
    }
    
    public void setIdRepaymentCancellation(Integer idRepaymentCancellation) {
        this.idRepaymentCancellation = idRepaymentCancellation;
    }
    public Repayment getRepayment() {
        return this.repayment;
    }
    
    public void setRepayment(Repayment repayment) {
        this.repayment = repayment;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getIsAproved() {
        return this.isAproved;
    }
    
    public void setIsAproved(String isAproved) {
        this.isAproved = isAproved;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


