package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Resignation generated by hbm2java
 */
public class Resignation  implements java.io.Serializable {


     private Integer idResignation;
     private Staff staff;
     private String requestDate;
     private String resihnationDate;
     private String reason;
     private String isActive;
     private String isAproved;
     private String createdBy;

    public Resignation() {
    }

	
    public Resignation(Staff staff) {
        this.staff = staff;
    }
    public Resignation(Staff staff, String requestDate, String resihnationDate, String reason, String isActive, String isAproved, String createdBy) {
       this.staff = staff;
       this.requestDate = requestDate;
       this.resihnationDate = resihnationDate;
       this.reason = reason;
       this.isActive = isActive;
       this.isAproved = isAproved;
       this.createdBy = createdBy;
    }
   
    public Integer getIdResignation() {
        return this.idResignation;
    }
    
    public void setIdResignation(Integer idResignation) {
        this.idResignation = idResignation;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(String requestDate) {
        this.requestDate = requestDate;
    }
    public String getResihnationDate() {
        return this.resihnationDate;
    }
    
    public void setResihnationDate(String resihnationDate) {
        this.resihnationDate = resihnationDate;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getIsAproved() {
        return this.isAproved;
    }
    
    public void setIsAproved(String isAproved) {
        this.isAproved = isAproved;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


