package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Staffattedence generated by hbm2java
 */
public class Staffattedence  implements java.io.Serializable {


     private Integer idStaffAttedence;
     private Staff staff;
     private String date;
     private String status;
     private String intime;
     private String outtime;
     private String specialnote;
     private String isDelete;
     private String isActive;
     private String isAprove;
     private String createdBy;

    public Staffattedence() {
    }

	
    public Staffattedence(Staff staff) {
        this.staff = staff;
    }
    public Staffattedence(Staff staff, String date, String status, String intime, String outtime, String specialnote, String isDelete, String isActive, String isAprove, String createdBy) {
       this.staff = staff;
       this.date = date;
       this.status = status;
       this.intime = intime;
       this.outtime = outtime;
       this.specialnote = specialnote;
       this.isDelete = isDelete;
       this.isActive = isActive;
       this.isAprove = isAprove;
       this.createdBy = createdBy;
    }
   
    public Integer getIdStaffAttedence() {
        return this.idStaffAttedence;
    }
    
    public void setIdStaffAttedence(Integer idStaffAttedence) {
        this.idStaffAttedence = idStaffAttedence;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getIntime() {
        return this.intime;
    }
    
    public void setIntime(String intime) {
        this.intime = intime;
    }
    public String getOuttime() {
        return this.outtime;
    }
    
    public void setOuttime(String outtime) {
        this.outtime = outtime;
    }
    public String getSpecialnote() {
        return this.specialnote;
    }
    
    public void setSpecialnote(String specialnote) {
        this.specialnote = specialnote;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getIsAprove() {
        return this.isAprove;
    }
    
    public void setIsAprove(String isAprove) {
        this.isAprove = isAprove;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


