package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * StaffHasDeductions generated by hbm2java
 */
public class StaffHasDeductions  implements java.io.Serializable {


     private Integer idStaffHasDeductions;
     private Deductions deductions;
     private Staff staff;
     private String date;
     private String amount;
     private String isActive;
     private String isaprove;
     private String createdBy;

    public StaffHasDeductions() {
    }

	
    public StaffHasDeductions(Deductions deductions, Staff staff) {
        this.deductions = deductions;
        this.staff = staff;
    }
    public StaffHasDeductions(Deductions deductions, Staff staff, String date, String amount, String isActive, String isaprove, String createdBy) {
       this.deductions = deductions;
       this.staff = staff;
       this.date = date;
       this.amount = amount;
       this.isActive = isActive;
       this.isaprove = isaprove;
       this.createdBy = createdBy;
    }
   
    public Integer getIdStaffHasDeductions() {
        return this.idStaffHasDeductions;
    }
    
    public void setIdStaffHasDeductions(Integer idStaffHasDeductions) {
        this.idStaffHasDeductions = idStaffHasDeductions;
    }
    public Deductions getDeductions() {
        return this.deductions;
    }
    
    public void setDeductions(Deductions deductions) {
        this.deductions = deductions;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getIsaprove() {
        return this.isaprove;
    }
    
    public void setIsaprove(String isaprove) {
        this.isaprove = isaprove;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }




}


