package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * Staffleave generated by hbm2java
 */
public class Staffleave  implements java.io.Serializable {


     private Integer idstaffLeave;
     private Staff staff;
     private String startDate;
     private String endDate;
     private String leaveType;
     private String isDelete;
     private String requestedDate;
     private String isAprove;
     private String isActive;
     private String createdBy;
     private String reason;
     private String totalDays;

    public Staffleave() {
    }

	
    public Staffleave(Staff staff) {
        this.staff = staff;
    }
    public Staffleave(Staff staff, String startDate, String endDate, String leaveType, String isDelete, String requestedDate, String isAprove, String isActive, String createdBy, String reason, String totalDays) {
       this.staff = staff;
       this.startDate = startDate;
       this.endDate = endDate;
       this.leaveType = leaveType;
       this.isDelete = isDelete;
       this.requestedDate = requestedDate;
       this.isAprove = isAprove;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.reason = reason;
       this.totalDays = totalDays;
    }
   
    public Integer getIdstaffLeave() {
        return this.idstaffLeave;
    }
    
    public void setIdstaffLeave(Integer idstaffLeave) {
        this.idstaffLeave = idstaffLeave;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }
    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public String getLeaveType() {
        return this.leaveType;
    }
    
    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getRequestedDate() {
        return this.requestedDate;
    }
    
    public void setRequestedDate(String requestedDate) {
        this.requestedDate = requestedDate;
    }
    public String getIsAprove() {
        return this.isAprove;
    }
    
    public void setIsAprove(String isAprove) {
        this.isAprove = isAprove;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getTotalDays() {
        return this.totalDays;
    }
    
    public void setTotalDays(String totalDays) {
        this.totalDays = totalDays;
    }




}


