package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer idStaff;
     private String nic;
     private String licenceNo;
     private String name;
     private String address1;
     private String address2;
     private String city;
     private String contact1;
     private String contact2;
     private String basicSalary;
     private String etfNo;
     private String epfNo;
     private String dob;
     private String joiningDate;
     private String position;
     private String isActive;
     private String createdby;
     private String email;
     private String gender;
     private String photo;
     private String nameWithinitials;
     private Set staffHasDeductionses = new HashSet(0);
     private Set staffattedences = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set centerHasStaffs = new HashSet(0);
     private Set resignations = new HashSet(0);
     private Set staffsalaries = new HashSet(0);
     private Set staffHasAllowances = new HashSet(0);
     private Set denimations = new HashSet(0);
     private Set staffleaves = new HashSet(0);

    public Staff() {
    }

    public Staff(String nic, String licenceNo, String name, String address1, String address2, String city, String contact1, String contact2, String basicSalary, String etfNo, String epfNo, String dob, String joiningDate, String position, String isActive, String createdby, String email, String gender, String photo, String nameWithinitials, Set staffHasDeductionses, Set staffattedences, Set logins, Set centerHasStaffs, Set resignations, Set staffsalaries, Set staffHasAllowances, Set denimations, Set staffleaves) {
       this.nic = nic;
       this.licenceNo = licenceNo;
       this.name = name;
       this.address1 = address1;
       this.address2 = address2;
       this.city = city;
       this.contact1 = contact1;
       this.contact2 = contact2;
       this.basicSalary = basicSalary;
       this.etfNo = etfNo;
       this.epfNo = epfNo;
       this.dob = dob;
       this.joiningDate = joiningDate;
       this.position = position;
       this.isActive = isActive;
       this.createdby = createdby;
       this.email = email;
       this.gender = gender;
       this.photo = photo;
       this.nameWithinitials = nameWithinitials;
       this.staffHasDeductionses = staffHasDeductionses;
       this.staffattedences = staffattedences;
       this.logins = logins;
       this.centerHasStaffs = centerHasStaffs;
       this.resignations = resignations;
       this.staffsalaries = staffsalaries;
       this.staffHasAllowances = staffHasAllowances;
       this.denimations = denimations;
       this.staffleaves = staffleaves;
    }
   
    public Integer getIdStaff() {
        return this.idStaff;
    }
    
    public void setIdStaff(Integer idStaff) {
        this.idStaff = idStaff;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getLicenceNo() {
        return this.licenceNo;
    }
    
    public void setLicenceNo(String licenceNo) {
        this.licenceNo = licenceNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getContact1() {
        return this.contact1;
    }
    
    public void setContact1(String contact1) {
        this.contact1 = contact1;
    }
    public String getContact2() {
        return this.contact2;
    }
    
    public void setContact2(String contact2) {
        this.contact2 = contact2;
    }
    public String getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(String basicSalary) {
        this.basicSalary = basicSalary;
    }
    public String getEtfNo() {
        return this.etfNo;
    }
    
    public void setEtfNo(String etfNo) {
        this.etfNo = etfNo;
    }
    public String getEpfNo() {
        return this.epfNo;
    }
    
    public void setEpfNo(String epfNo) {
        this.epfNo = epfNo;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getJoiningDate() {
        return this.joiningDate;
    }
    
    public void setJoiningDate(String joiningDate) {
        this.joiningDate = joiningDate;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getNameWithinitials() {
        return this.nameWithinitials;
    }
    
    public void setNameWithinitials(String nameWithinitials) {
        this.nameWithinitials = nameWithinitials;
    }
    public Set getStaffHasDeductionses() {
        return this.staffHasDeductionses;
    }
    
    public void setStaffHasDeductionses(Set staffHasDeductionses) {
        this.staffHasDeductionses = staffHasDeductionses;
    }
    public Set getStaffattedences() {
        return this.staffattedences;
    }
    
    public void setStaffattedences(Set staffattedences) {
        this.staffattedences = staffattedences;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getCenterHasStaffs() {
        return this.centerHasStaffs;
    }
    
    public void setCenterHasStaffs(Set centerHasStaffs) {
        this.centerHasStaffs = centerHasStaffs;
    }
    public Set getResignations() {
        return this.resignations;
    }
    
    public void setResignations(Set resignations) {
        this.resignations = resignations;
    }
    public Set getStaffsalaries() {
        return this.staffsalaries;
    }
    
    public void setStaffsalaries(Set staffsalaries) {
        this.staffsalaries = staffsalaries;
    }
    public Set getStaffHasAllowances() {
        return this.staffHasAllowances;
    }
    
    public void setStaffHasAllowances(Set staffHasAllowances) {
        this.staffHasAllowances = staffHasAllowances;
    }
    public Set getDenimations() {
        return this.denimations;
    }
    
    public void setDenimations(Set denimations) {
        this.denimations = denimations;
    }
    public Set getStaffleaves() {
        return this.staffleaves;
    }
    
    public void setStaffleaves(Set staffleaves) {
        this.staffleaves = staffleaves;
    }




}


