package ORM;
// Generated Apr 6, 2018 6:20:29 PM by Hibernate Tools 4.3.1



/**
 * StaffHasAllowance generated by hbm2java
 */
public class StaffHasAllowance  implements java.io.Serializable {


     private Integer idStaffHasAllowance;
     private Allowance allowance;
     private Staff staff;
     private String date;
     private String amount;

    public StaffHasAllowance() {
    }

	
    public StaffHasAllowance(Allowance allowance, Staff staff) {
        this.allowance = allowance;
        this.staff = staff;
    }
    public StaffHasAllowance(Allowance allowance, Staff staff, String date, String amount) {
       this.allowance = allowance;
       this.staff = staff;
       this.date = date;
       this.amount = amount;
    }
   
    public Integer getIdStaffHasAllowance() {
        return this.idStaffHasAllowance;
    }
    
    public void setIdStaffHasAllowance(Integer idStaffHasAllowance) {
        this.idStaffHasAllowance = idStaffHasAllowance;
    }
    public Allowance getAllowance() {
        return this.allowance;
    }
    
    public void setAllowance(Allowance allowance) {
        this.allowance = allowance;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }




}


