-- MySQL Script generated by MySQL Workbench
-- Sat 07 Apr 2018 09:49:20 AM +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema microcredit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema microcredit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `microcredit` DEFAULT CHARACTER SET latin1 ;
USE `microcredit` ;

-- -----------------------------------------------------
-- Table `microcredit`.`allowance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`allowance` (
  `idAllowance` INT(11) NOT NULL AUTO_INCREMENT,
  `AllowancName` VARCHAR(45) NULL DEFAULT NULL,
  `Isdelete` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `IsAprove` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idAllowance`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`branch` (
  `idBranch` INT(11) NOT NULL AUTO_INCREMENT,
  `BranchNo` VARCHAR(45) NULL DEFAULT NULL,
  `BranchName` VARCHAR(45) NULL DEFAULT NULL,
  `Address1` VARCHAR(45) NULL DEFAULT NULL,
  `Address2` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `Contact1` VARCHAR(45) NULL DEFAULT NULL,
  `Contact2` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idBranch`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`center` (
  `idCenter` INT(11) NOT NULL AUTO_INCREMENT,
  `idBranch` INT(11) NOT NULL,
  `CenterName` VARCHAR(45) NULL DEFAULT NULL,
  `CenterDay` VARCHAR(45) NULL DEFAULT NULL,
  `Centertime` VARCHAR(45) NULL DEFAULT NULL,
  `IsApprove` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(10) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `CenterNO` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idCenter`),
  INDEX `fk_Center_Branch_idx` (`idBranch` ASC),
  CONSTRAINT `fk_Center_Branch`
    FOREIGN KEY (`idBranch`)
    REFERENCES `microcredit`.`branch` (`idBranch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`staff` (
  `idStaff` INT(11) NOT NULL AUTO_INCREMENT,
  `Nic` VARCHAR(45) NULL DEFAULT NULL,
  `LicenceNo` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `Address1` VARCHAR(45) NULL DEFAULT NULL,
  `Address2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `Contact1` VARCHAR(45) NULL DEFAULT NULL,
  `contact2` VARCHAR(45) NULL DEFAULT NULL,
  `Basic Salary` VARCHAR(45) NULL DEFAULT NULL,
  `EtfNo` VARCHAR(45) NULL DEFAULT NULL,
  `EpfNo` VARCHAR(45) NULL DEFAULT NULL,
  `DOB` VARCHAR(45) NULL DEFAULT NULL,
  `joiningDate` VARCHAR(45) NULL DEFAULT NULL,
  `Position` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `Createdby` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Gender` VARCHAR(45) NULL DEFAULT NULL,
  `Photo` VARCHAR(45) NULL DEFAULT NULL,
  `NameWithinitials` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idStaff`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`center_has_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`center_has_staff` (
  `IDCenter_has_Staff` INT(11) NOT NULL AUTO_INCREMENT,
  `idCenter` INT(11) NOT NULL,
  `idStaff` INT(11) NOT NULL,
  PRIMARY KEY (`IDCenter_has_Staff`),
  INDEX `fk_Center_has_Staff_Staff1_idx` (`idStaff` ASC),
  INDEX `fk_Center_has_Staff_Center1_idx` (`idCenter` ASC),
  CONSTRAINT `fk_Center_has_Staff_Center1`
    FOREIGN KEY (`idCenter`)
    REFERENCES `microcredit`.`center` (`idCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Center_has_Staff_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`deductions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`deductions` (
  `idDeductions` INT(11) NOT NULL AUTO_INCREMENT,
  `DeductionType` VARCHAR(45) NULL DEFAULT NULL,
  `IsDelete` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDeductions`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`denimation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`denimation` (
  `idDenimation` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `ExchangeCash` DOUBLE NULL DEFAULT NULL,
  `CenterCollection` DOUBLE NULL DEFAULT NULL,
  `NPCollection` DOUBLE NULL DEFAULT NULL,
  `MemberFee` DOUBLE NULL DEFAULT NULL,
  `IncomeAmount` DOUBLE NULL DEFAULT NULL,
  `TotalLoanAmount` DOUBLE NULL DEFAULT NULL,
  `Expences` DOUBLE NULL DEFAULT NULL,
  `TotalBalance` DOUBLE NULL DEFAULT NULL,
  `Short` DOUBLE NULL DEFAULT NULL,
  `Extras` DOUBLE NULL DEFAULT NULL,
  `ShortAndExtraBalance` DOUBLE NULL DEFAULT NULL,
  `idStaff` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idDenimation`),
  INDEX `fk_Denimation_Staff1` (`idStaff` ASC),
  CONSTRAINT `fk_Denimation_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`denimationcah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`denimationcah` (
  `idDenimationCah` INT(11) NOT NULL AUTO_INCREMENT,
  `idDenimation` INT(11) NOT NULL,
  `N5000` INT(11) NULL DEFAULT NULL,
  `N2000` INT(11) NULL DEFAULT NULL,
  `N1000` INT(11) NULL DEFAULT NULL,
  `N500` INT(11) NULL DEFAULT NULL,
  `N100` INT(11) NULL DEFAULT NULL,
  `N50` INT(11) NULL DEFAULT NULL,
  `N20` INT(11) NULL DEFAULT NULL,
  `N10` INT(11) NULL DEFAULT NULL,
  `Coins` DOUBLE NULL DEFAULT NULL,
  `Total` DOUBLE NULL DEFAULT NULL,
  `SlipNo` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`idDenimationCah`),
  INDEX `fk_DenimationCah_Denimation1_idx` (`idDenimation` ASC),
  CONSTRAINT `fk_DenimationCah_Denimation1`
    FOREIGN KEY (`idDenimation`)
    REFERENCES `microcredit`.`denimation` (`idDenimation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`members` (
  `idMembers` INT(11) NOT NULL AUTO_INCREMENT,
  `MemberNo` VARCHAR(45) NULL DEFAULT NULL,
  `GroupId` VARCHAR(45) NULL DEFAULT NULL,
  `NameWithInitials` VARCHAR(45) NULL DEFAULT NULL,
  `FullName` VARCHAR(100) NULL DEFAULT NULL,
  `Nic` VARCHAR(45) NULL DEFAULT NULL,
  `DOB` VARCHAR(45) NULL DEFAULT NULL,
  `Address1` VARCHAR(45) NULL DEFAULT NULL,
  `Address2` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `ContactNo` VARCHAR(45) NULL DEFAULT NULL,
  `HusbandName` VARCHAR(45) NULL DEFAULT NULL,
  `HusbandNic` VARCHAR(45) NULL DEFAULT NULL,
  `Husbandjob` VARCHAR(45) NULL DEFAULT NULL,
  `HusbandDOB` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `Aproved` VARCHAR(45) NULL DEFAULT NULL,
  `idCenter` INT(11) NOT NULL,
  PRIMARY KEY (`idMembers`),
  INDEX `fk_Members_Center1_idx` (`idCenter` ASC),
  CONSTRAINT `fk_Members_Center1`
    FOREIGN KEY (`idCenter`)
    REFERENCES `microcredit`.`center` (`idCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`loan` (
  `idLoan` INT(11) NOT NULL AUTO_INCREMENT,
  `ContractNo` VARCHAR(45) NULL DEFAULT NULL,
  `LoanAmount` DOUBLE NULL DEFAULT NULL,
  `LoanInterest` DOUBLE NULL DEFAULT NULL,
  `LoanPeriod` INT(11) NULL DEFAULT NULL,
  `LoanInstallment` DOUBLE NULL DEFAULT NULL,
  `Memberfee` VARCHAR(45) NULL DEFAULT NULL,
  `LoanIndex` VARCHAR(45) NULL DEFAULT NULL,
  `RepaymentDay` VARCHAR(45) NULL DEFAULT NULL,
  `LoanDate` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `garanter1` VARCHAR(200) NULL DEFAULT NULL,
  `garanter2` VARCHAR(200) NULL DEFAULT NULL,
  `IsAprove` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `CreateBy` VARCHAR(45) NULL DEFAULT NULL,
  `idMembers` INT(11) NOT NULL,
  `RenewAmount` DOUBLE NULL DEFAULT NULL,
  `issueDate` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idLoan`),
  INDEX `fk_Loan_Members1_idx` (`idMembers` ASC),
  CONSTRAINT `fk_Loan_Members1`
    FOREIGN KEY (`idMembers`)
    REFERENCES `microcredit`.`members` (`idMembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`legalaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`legalaction` (
  `idLegalAction` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `Reason` VARCHAR(45) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `idMembers` INT(11) NOT NULL,
  `idLoan` INT(11) NOT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `IsAproved` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLegalAction`),
  INDEX `fk_LegalAction_Members1_idx` (`idMembers` ASC),
  INDEX `fk_LegalAction_Loan1_idx` (`idLoan` ASC),
  CONSTRAINT `fk_LegalAction_Loan1`
    FOREIGN KEY (`idLoan`)
    REFERENCES `microcredit`.`loan` (`idLoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LegalAction_Members1`
    FOREIGN KEY (`idMembers`)
    REFERENCES `microcredit`.`members` (`idMembers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`loancancellation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`loancancellation` (
  `idLoanCancellation` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `Reason` VARCHAR(45) NULL DEFAULT NULL,
  `IsAproved` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `CreaedBy` VARCHAR(45) NULL DEFAULT NULL,
  `idLoan` INT(11) NOT NULL,
  PRIMARY KEY (`idLoanCancellation`),
  INDEX `fk_LoanCancellation_Loan1_idx` (`idLoan` ASC),
  CONSTRAINT `fk_LoanCancellation_Loan1`
    FOREIGN KEY (`idLoan`)
    REFERENCES `microcredit`.`loan` (`idLoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`login` (
  `idLogin` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  `SetDate` VARCHAR(45) NULL DEFAULT NULL,
  `idStaff` INT(11) NOT NULL,
  `loginBlock` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `IsAprove` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Staff1_idx` (`idStaff` ASC),
  CONSTRAINT `fk_Login_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`printvoucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`printvoucher` (
  `idPrintVoucher` INT(11) NOT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `Amount` VARCHAR(45) NULL DEFAULT NULL,
  `Isactive` VARCHAR(45) NULL DEFAULT NULL,
  `IsAprove` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPrintVoucher`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`repayment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`repayment` (
  `idRePayment` INT(11) NOT NULL AUTO_INCREMENT,
  `RepaymentAmount` DOUBLE NULL DEFAULT NULL,
  `PaidAmount` DOUBLE NULL DEFAULT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `ActualDay` VARCHAR(45) NULL DEFAULT NULL,
  `CurrentDay` VARCHAR(45) NULL DEFAULT NULL,
  `idLoan` INT(11) NOT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `IsAproved` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `RecieptNo` VARCHAR(45) NULL DEFAULT NULL,
  `Arreas` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idRePayment`),
  INDEX `fk_RePayment_Loan1_idx` (`idLoan` ASC),
  CONSTRAINT `fk_RePayment_Loan1`
    FOREIGN KEY (`idLoan`)
    REFERENCES `microcredit`.`loan` (`idLoan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`repaymentcancellation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`repaymentcancellation` (
  `idRepaymentCancellation` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `Reason` VARCHAR(45) NULL DEFAULT NULL,
  `IsAproved` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `idRePayment` INT(11) NOT NULL,
  PRIMARY KEY (`idRepaymentCancellation`),
  INDEX `fk_RepaymentCancellation_RePayment1_idx` (`idRePayment` ASC),
  CONSTRAINT `fk_RepaymentCancellation_RePayment1`
    FOREIGN KEY (`idRePayment`)
    REFERENCES `microcredit`.`repayment` (`idRePayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`resignation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`resignation` (
  `idResignation` INT(11) NOT NULL AUTO_INCREMENT,
  `Request Date` VARCHAR(45) NULL DEFAULT NULL,
  `Resihnation Date` VARCHAR(45) NULL DEFAULT NULL,
  `Reason` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `IsAproved` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `idStaff` INT(11) NOT NULL,
  PRIMARY KEY (`idResignation`),
  INDEX `fk_Resignation_Staff1_idx` (`idStaff` ASC),
  CONSTRAINT `fk_Resignation_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`staff_has_allowance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`staff_has_allowance` (
  `idStaff` INT(11) NOT NULL,
  `idAllowance` INT(11) NOT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `Amount` VARCHAR(45) NULL DEFAULT NULL,
  `idStaff_has_Allowance` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idStaff_has_Allowance`),
  INDEX `fk_Staff_has_Allowance_Allowance1_idx` (`idAllowance` ASC),
  INDEX `fk_Staff_has_Allowance_Staff1_idx` (`idStaff` ASC),
  CONSTRAINT `fk_Staff_has_Allowance_Allowance1`
    FOREIGN KEY (`idAllowance`)
    REFERENCES `microcredit`.`allowance` (`idAllowance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_has_Allowance_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`staff_has_deductions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`staff_has_deductions` (
  `idStaff` INT(11) NOT NULL,
  `idDeductions` INT(11) NOT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `Amount` VARCHAR(45) NULL DEFAULT NULL,
  `idStaff_has_Deductions` INT(11) NOT NULL AUTO_INCREMENT,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `Isaprove` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idStaff_has_Deductions`),
  INDEX `fk_Staff_has_Deductions_Deductions1_idx` (`idDeductions` ASC),
  INDEX `fk_Staff_has_Deductions_Staff1_idx` (`idStaff` ASC),
  CONSTRAINT `fk_Staff_has_Deductions_Deductions1`
    FOREIGN KEY (`idDeductions`)
    REFERENCES `microcredit`.`deductions` (`idDeductions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Staff_has_Deductions_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`staffattedence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`staffattedence` (
  `idStaffAttedence` INT(11) NOT NULL AUTO_INCREMENT,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `Intime` VARCHAR(45) NULL DEFAULT NULL,
  `Outtime` VARCHAR(45) NULL DEFAULT NULL,
  `Specialnote` VARCHAR(45) NULL DEFAULT NULL,
  `isDelete` VARCHAR(45) NULL DEFAULT NULL,
  `idStaff` INT(11) NOT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `IsAprove` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idStaffAttedence`),
  INDEX `fk_StaffAttedence_Staff1_idx` (`idStaff` ASC),
  CONSTRAINT `fk_StaffAttedence_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`staffleave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`staffleave` (
  `idstaffLeave` INT(11) NOT NULL AUTO_INCREMENT,
  `StartDate` VARCHAR(45) NULL DEFAULT NULL,
  `EndDate` VARCHAR(45) NULL DEFAULT NULL,
  `LeaveType` VARCHAR(45) NULL DEFAULT NULL,
  `isDelete` VARCHAR(45) NULL DEFAULT NULL,
  `idStaff` INT(11) NOT NULL,
  `RequestedDate` VARCHAR(45) NULL DEFAULT NULL,
  `IsAprove` VARCHAR(45) NULL DEFAULT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `Reason` VARCHAR(45) NULL DEFAULT NULL,
  `TotalDays` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idstaffLeave`),
  INDEX `fk_staffLeave_Staff1_idx` (`idStaff` ASC),
  CONSTRAINT `fk_staffLeave_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`staffsalary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`staffsalary` (
  `idStaffSalary` INT(11) NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `BasicSalary` VARCHAR(45) NULL DEFAULT NULL,
  `TotalSalary` VARCHAR(45) NULL DEFAULT NULL,
  `TotalAllowance` VARCHAR(45) NULL DEFAULT NULL,
  `totalDeductions` VARCHAR(45) NULL DEFAULT NULL,
  `Etf` VARCHAR(45) NULL DEFAULT NULL,
  `Epf` VARCHAR(45) NULL DEFAULT NULL,
  `NetSalary` VARCHAR(45) NULL DEFAULT NULL,
  `isDelete` VARCHAR(45) NULL DEFAULT NULL,
  `TotalPayments` VARCHAR(45) NULL DEFAULT NULL,
  `idStaff` INT(11) NOT NULL,
  `IsActive` VARCHAR(45) NULL DEFAULT NULL,
  `IsAprove` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idStaffSalary`),
  INDEX `fk_StaffSalary_Staff1_idx` (`idStaff` ASC),
  CONSTRAINT `fk_StaffSalary_Staff1`
    FOREIGN KEY (`idStaff`)
    REFERENCES `microcredit`.`staff` (`idStaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `microcredit`.`DayEnd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`DayEnd` (
  `idDayEnd` INT NOT NULL AUTO_INCREMENT,
  `DayEndDate` VARCHAR(45) NULL,
  `DayEndTime` VARCHAR(45) NULL,
  PRIMARY KEY (`idDayEnd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microcredit`.`LoanAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`LoanAccount` (
  `idLoanAcc` INT NOT NULL AUTO_INCREMENT,
  `AccDate` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Credit` DOUBLE NULL,
  `Debit` DOUBLE NULL,
  `IsActive` VARCHAR(45) NULL,
  `CreateBy` VARCHAR(45) NULL,
  PRIMARY KEY (`idLoanAcc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microcredit`.`InterestAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`InterestAccount` (
  `idIntAcc` INT NOT NULL AUTO_INCREMENT,
  `AccDate` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Credit` DOUBLE NULL,
  `Debit` DOUBLE NULL,
  `IsActive` VARCHAR(45) NULL,
  `CreateBy` VARCHAR(45) NULL,
  PRIMARY KEY (`idIntAcc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microcredit`.`AccruedIncomeAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`AccruedIncomeAccount` (
  `idAcInAcc` INT NOT NULL AUTO_INCREMENT,
  `AccDate` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Credit` DOUBLE NULL,
  `Debit` DOUBLE NULL,
  `IsActive` VARCHAR(45) NULL,
  `CreateBy` VARCHAR(45) NULL,
  PRIMARY KEY (`idAcInAcc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microcredit`.`CashInHandAcc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`CashInHandAcc` (
  `idCashIn` INT NOT NULL AUTO_INCREMENT,
  `AccDate` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Credit` DOUBLE NULL,
  `Debit` DOUBLE NULL,
  `IsActive` VARCHAR(45) NULL,
  `CreateBy` VARCHAR(45) NULL,
  PRIMARY KEY (`idCashIn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `microcredit`.`OtherIncomeAcc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `microcredit`.`OtherIncomeAcc` (
  `idOtherIncome` INT NOT NULL AUTO_INCREMENT,
  `AccDate` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Credit` DOUBLE NULL,
  `Debit` DOUBLE NULL,
  `IsActive` VARCHAR(45) NULL,
  `CreateBy` VARCHAR(45) NULL,
  PRIMARY KEY (`idOtherIncome`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
